name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your main branch name if different
  pull_request:
    branches:
      - main # Replace with your main branch name if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Or 'beta' or 'dev'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          # The branch history should be used on gh-pages branch.
          # When using main, uncomment below:
          # publish_branch: main
          # When using gh-pages, uncomment below:
          publish_branch: gh-pages
